---
- name: Perform apt-get update and upgrade
  hosts: all
  become: true

  tasks:
    - name: Run apt-get update
      apt:
        update_cache: yes

    - name: Run apt-get upgrade
      apt:
        upgrade: dist
        update_cache: yes
        force_apt_get: yes
