
---
- name: List only user accounts
  hosts: all
  become: true

  # works by differing system users and normal users by id - greater then 1000 and smaller then 60000
  tasks:
    - name: Get user accounts
      shell: "awk -F: '($3>=1000)&&($3<60000)&&($1!=\"nobody\"){print}' /etc/passwd"
      register: acounts

    - name: List user accounts
      debug:
        var: acounts.stdout_lines
